name: edit-gcs-bucket

on:
  push:
    branches: [ "main" ]

env:
  BUCKET_NAME: jetblue-dotcom-i18n

jobs:
  upload_file:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
      with:
          fetch-depth: 0
    - name: Get all changed *.json file(s) or any file in the static folder excluding the docs folder
      id: changed-files-excluded
      uses: tj-actions/changed-files@v35
      with:
          files: |
            **/*.json
            static
          files_ignore: workflows

    - name: Run step if any *.js file(s) or any file in the static folder change
      if: steps.changed-files-excluded.outputs.any_changed == 'true'
      run: |
          echo "One or more *.js file(s) or any file in the static folder but not in the doc folder has changed."
          echo "List all the files that have changed: ${{ steps.changed-files-excluded.outputs.all_changed_files }}"
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
        #workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        #service_account: 'my-service-account@my-project.iam.gserviceaccount.com'
    - name: List all changed files
      run: |
          for file in ${{ steps.changed-files-excluded.outputs.all_changed_files }}; do
            echo "$file was changed"
            - id: 'upload-file'
              uses: 'google-github-actions/upload-cloud-storage@v1'
              with:
                path: '$file'
                destination: '${{env.BUCKET_NAME}}/test3'
          done
    - id: 'upload-file'
      uses: 'google-github-actions/upload-cloud-storage@v1'
      with:
        path: '${{ steps.changed-files-excluded.outputs.all_changed_files }}'
        destination: '${{env.BUCKET_NAME}}/test3'

    # Example of using the output
    # - id: 'uploaded-files'
    #   uses: 'foo/bar@main'
    #   env:
    #     file: '${{ steps.upload-file.outputs.uploaded }}'
