name: edit-gcs-bucket

on:
  push:
    branches: [ "main" ]

env:
  BUCKET_NAME: jetblue-dotcom-i18n

jobs:
  get-files:
    runs-on: ubuntu-latest
    name: Get modified files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: |
            **/*.json
            static
          files_ignore: workflows
      - name: List all changed files
        run: |
          echo "${{ steps.changed-files.outputs.all_modified_files }}"
      - name: Set the value
        id: step_one
        run: |
          echo "action_state=$(echo "${{ steps.changed-files.outputs.all_modified_files }}" |sed 's/^/["/;s/$/"]/;s/ /\",\"/g')" >> $GITHUB_ENV
      - name: Use the value
        id: step_two
        run: |
          echo ${{ env.action_state }}
    outputs:
      matrix: ${{ env.action_state }}
  upload_file:
    needs: [ get-files ]
    if: fromJson(needs.get-files.outputs.matrix)[0] != null
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: "${{fromJson(needs.get-files.outputs.matrix)}}"
    steps:
    - name: checkout repo
      uses: actions/checkout@v3
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
        #workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        #service_account: 'my-service-account@my-project.iam.gserviceaccount.com'
    - run: |
        echo "file_path=$(echo "${{ matrix.value }}" |sed 's%/[^/]*$%%')" >> $GITHUB_ENV
    - run: |
        echo "${{ env.file_path }}"
    - id: 'upload-file'
      uses: 'google-github-actions/upload-cloud-storage@v1'
      with:
        path: '${{ matrix.value }}'
        destination: '${{env.BUCKET_NAME}}/${{ env.file_path }}'
